churchapp/urls.py
# type:ignore
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from .views import home,Events,AdminSignUpView,ClientSignUpView,review_form,cermon_form,event_form,impact_form,impact_category_form,payment_method_form,gallery_form,faq_form,team_form

app_name = 'churchapp'


urlpatterns = [
    path('',home,name="home"),
    path('events/',Events,name="events"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('accounts/signup/admin/3567/', AdminSignUpView.as_view(), name='admin_signup'),
    path('accounts/signup/client/', ClientSignUpView.as_view(), name='client_signup'),
    path('add/testimony/form/',review_form,name='review_form'),
    path('add/sermon/form/',cermon_form,name='cermon_form'),
    path('add/event/form/',event_form,name='event_form'),
    path('add/impact/category/form/',impact_category_form,name='impact_category_form'),
    path('add/impact/form/',impact_form,name='impact_form'),
    path('add/payment/method/form/',payment_method_form,name='payment_form'),
    path('add/gallery-image/form/',gallery_form,name='gallery_form'),
    path('add/new-member/form/',team_form,name='team_form'),
    path('add/FAQ/form/',faq_form,name='faq_form'),



    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

churchproject/urls.py
# type:ignore
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('churchapp.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
]

churchapp/forms.py
# type:ignore
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,Admin,Client,User,Review,Cermon,ImpactCategory,Impact,Event,PaymentMethod,Gallery,Team,Faq
from django.db import transaction


class AdminSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = True
        user.save()
        admin = Admin.objects.create(user=user)
        admin.save()
        return user

class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_client = True
        user.save()
        client = Client.objects.create(user=user)
        client.save()
        return user

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email')

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'location', 'profile_pic')


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('profile_pic','first_name','last_name','comment')

class CermonForm(forms.ModelForm):
    class Meta:
        model = Cermon
        fields = ('theme','description','reading','link','date','image')

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('title','description','event_date','image')

class ImpactCategoryForm(forms.ModelForm):
    class Meta:
        model = ImpactCategory
        fields = ('name',)


class ImpactForm(forms.ModelForm):
    class Meta:
        model = Impact
        fields = ('title','description','category','image')

class PaymentForm(forms.ModelForm):
    class Meta:
        model = PaymentMethod
        fields = ('method','email','till','paybill','account')

class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ('category','image')


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('name','rank','image')

class FaqForm(forms.ModelForm):
    class Meta:
        model = Faq
        fields = ('question','answer')

churchapp/views.py
# type:ignore
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from .forms import UpdateUserForm,UpdateProfileForm,ClientSignUpForm,AdminSignUpForm,ReviewForm,CermonForm,EventForm,ImpactCategoryForm,ImpactForm,PaymentForm,GalleryForm,FaqForm,TeamForm
from .models import User,Profile,Review,Cermon,ImpactCategory,Impact,Event,PaymentMethod,Gallery,Team,Faq
from django.views.generic import CreateView
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger,EmptyPage




def home(request):
    reviews = Review.objects.all()
    cermons = Cermon.objects.all()
    excluded_categories = ['economical', 'social','technology']  # Names of categories to exclude
    remaining = ImpactCategory.objects.exclude(name__in=excluded_categories)
    for remained in remaining:
        impact_items = Impact.objects.filter(category = remained)

    s =ImpactCategory.objects.filter(name='social').first()
    t =ImpactCategory.objects.filter(name='technology').first()
    e =ImpactCategory.objects.filter(name='economical').first()
    social = Impact.objects.filter(category = s).all()
    technology = Impact.objects.filter(category = t).all()
    economical = Impact.objects.filter(category = e).all()
    donation_methods = PaymentMethod.objects.all()
    ministry = Gallery.objects.filter(category ="ministry").all()
    outreach = Gallery.objects.filter(category ="outreach").all()
    donation = Gallery.objects.filter(category ="donation").all()
    faqs = Faq.objects.all()
    members = Team.objects.all()
    context = {
        "reviews": reviews,
        "cermons":cermons,
        "impacts":impact_items,
        "donation_methods":donation_methods,
        "social":social,
        "technology":technology,
        "economical":economical,
        "donation":donation,
        "outreach":outreach,
        "ministry":ministry,
        "faqs":faqs,
        "members":members,
               }

    return render(request, 'index.html',context)

def Events(request):
    products_db = Event.objects.all()
    paginator = Paginator(products_db, 3)
    page = request.GET.get('page')
    count = paginator.get_page(page)
    total_pages = count.paginator.num_pages
    try:
        events = paginator.get_page(page)
    except PageNotAnInteger:
       events = paginator.get_page(1)
    except EmptyPage:
        events = paginator.get_page(paginator.num_pages)
    context= {
        "events": events,
        "total_pages": total_pages,
        "count":count,
    }
    return render(request, 'blog.html',context)

class AdminSignUpView(CreateView):
    model = User
    form_class = AdminSignUpForm
    template_name = 'registration/register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'admin'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('login')

class ClientSignUpView(CreateView):
    model = User
    form_class = ClientSignUpForm
    template_name = 'registration/register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('login')





@login_required(login_url='login')
def review_form(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'testimony was added successfully!')
            return redirect('churchapp:home')
    else:
        form = ReviewForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'review_form.html', { "form":form})


@login_required(login_url='login')
def cermon_form(request):
    if request.method == 'POST':
        form = CermonForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sermon added successfully!')
            return redirect('churchapp:home')
    else:
        form = CermonForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})

@login_required(login_url='login')
def event_form(request):
    if request.method == 'POST':
        form = EventForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Event added successfully!')
            return redirect('churchapp:home')
    else:
        form = EventForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})

@login_required(login_url='login')
def impact_category_form(request):
    if request.method == 'POST':
        form = ImpactCategoryForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category added successfully!')
            return redirect('churchapp:home')
    else:
        form = ImpactCategoryForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})

@login_required(login_url='login')
def impact_form(request):
    if request.method == 'POST':
        form = ImpactForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Impact item added successfully!')
            return redirect('churchapp:home')
    else:
        form = ImpactForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})

@login_required(login_url='login')
def payment_method_form(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Payment method added successfully!')
            return redirect('churchapp:home')
    else:
        form = PaymentForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})

@login_required(login_url='login')
def gallery_form(request):
    if request.method == 'POST':
        form = GalleryForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Gallery Image added successfully!')
            return redirect('churchapp:home')
    else:
        form = GalleryForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})


@login_required(login_url='login')
def faq_form(request):
    if request.method == 'POST':
        form = FaqForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Faqs added successfully!')
            return redirect('churchapp:home')
    else:
        form =FaqForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})


@login_required(login_url='login')
def team_form(request):
    if request.method == 'POST':
        form = TeamForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Member added successfully!')
            return redirect('churchapp:home')
    else:
        form =TeamForm()
        messages.error(request, 'Correct the error below')

    return render(request, 'cermon_form.html', { "form":form})
    

# @login_required(login_url='login')
# def profile(request, username):
#     return render(request, 'profile.html')

# @login_required(login_url='login')
# def edit_profile(request, username):
#     user = User.objects.get(username=username)
#     Profile.objects.get_or_create(user=request.user)
#     if request.method == 'POST':
#         user_form = UpdateUserForm(request.POST, instance=request.user)
#         prof_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
#         if user_form.is_valid() and prof_form.is_valid():
#             user_form.save()
#             prof_form.save()
#             # messages.success(request, 'Your profile was updated successfully!')
#             return redirect('kiddoApp:profile', user.username)
#     else:
#         # messages.error(request, 'Please correct the error below!')
#         user_form = UpdateUserForm(instance=request.user)
#         prof_form = UpdateProfileForm(instance=request.user.profile)
    
#     return render(request, 'editprofile.html', {'user_form': user_form, 'prof_form': prof_form})


# def home(request):
#     if request.user.is_authenticated:
#         Profile.objects.get_or_create(user=request.user)
#     else:
# 		# if not, create an anonymous user and log them in
#         username = get_random_string(length=32)
#         u = User(username=username, first_name='Anonymous', last_name='User')
#         u.set_unusable_password()
#         u.save()
#         u.username = u.id
#         u.save()
#         Profile.objects.get_or_create(user=u)
#         authenticate(user=u)
#         login(request, u)
    

#     return render(request, 'index.html')

churchapp/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Restoration Grace Chapel - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    {% block styles %}
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.cs' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% endblock styles %}

</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}


    {% endblock content %}



    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>Rostoration Grace<span>.</span></h3>
                        <p>
                            00100 Kibera drive<br>
                            Nairobi<br>
                            Kenya KE <br><br>
                            <strong>Phone:</strong> +254 112 5496 11<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'churchapp:home' %}">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#about">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#pricing">Donate</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#tabs">Impact</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#team">Team</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'churchapp:events' %}">Events</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#cermon">Sermon</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Join Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="https://formspree.io/f/mlekdvvb" method="POST" role="form">
                            <input type="email" name="email">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>Nanesoft-lab</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    Designed by <a href="https://nanesoft-lab.com">Nanesoft</a>
                </div>
            </div>
            <div class="social-links text-center text-md-end pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    {% block scripts %}
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% endblock scripts %}

</body>

</html>

churchapp/templates/blog.html
  {% extends 'base.html' %}
  {% load static %}
  {% load bootstrap4 %}
  {% block content %}
  <br><br>
  <main id="main" class="mt-5">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{% url 'churchapp:home' %}">Home</a></li>
          <li>Events</li>
        </ol>
        <h2>Events</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for event in events %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{event.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{{event.image.url}}">{{event.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{{event.image.url}}">Restoration</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="{{event.image.url}}"><time datetime="{{event.event_date}}">{{event.event_date}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{{event.image.url}}">12 to attend</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{event.description}}
                </p>
                <div class="read-more">
                  <a href="{{event.image.url}}">Read More</a>
                </div>
              </div>

            </article>
            {% endfor %}
            <!-- End blog entry -->

            <div class="ml-auto mt-3 mr-2">
              <nav aria-label="Page navigation example">
                  <ul class="pagination">
                      <li class="page-item"> 
                          {% if events.has_previous %}
                          <a class="page-link" href="?page={{ events.previous_page_number }}" aria-label="Previous"> <span aria-hidden="true"
                                  class="font-weight-bold">&lt;</span> <span class="sr-only">Previous</span> </a> 
                                  {% endif %}
                              </li>
                      <li class="page-item active"><a class="page-link" href="#" style="background-color: #dc3545;">{{count.number}}</a></li>
                      <li class="page-item"><a class="page-link" href="#" style="color: #dc3545;">Of</a></li>
                      <li class="page-item"><a class="page-link" href="#" style="color: #fff;background-color: #dc3545;">{{total_pages}}</a></li>
                      <li class="page-item">
                          {% if products.has_next %}            
                          <a class="page-link"  href="?page={{ events.next_page_number }}" aria-label="Next"> <span aria-hidden="true"
                                  class="font-weight-bold">&gt;</span> <span class="sr-only">Next</span> </a>
                                  {% endif %} 
                              </li>
                  </ul>
              </nav>
          </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  <li><a href="#">General <span>(25)</span></a></li>
                  <li><a href="#">Lifestyle <span>(12)</span></a></li>
                  <li><a href="#">Travel <span>(5)</span></a></li>
                  <li><a href="#">Design <span>(22)</span></a></li>
                  <li><a href="#">Creative <span>(8)</span></a></li>
                  <li><a href="#">Educaion <span>(14)</span></a></li>
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title">Recent Posts</h3>
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-1.jpg" alt="">
                  <h4><a href="blog-single.html">Nihil blanditiis at in nihil autem</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-2.jpg" alt="">
                  <h4><a href="blog-single.html">Quidem autem et impedit</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-3.jpg" alt="">
                  <h4><a href="blog-single.html">Id quia et et ut maxime similique occaecati ut</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-4.jpg" alt="">
                  <h4><a href="blog-single.html">Laborum corporis quo dara net para</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

                <div class="post-item clearfix">
                  <img src="assets/img/blog/blog-recent-5.jpg" alt="">
                  <h4><a href="blog-single.html">Et dolores corrupti quae illo quod dolor</a></h4>
                  <time datetime="2020-01-01">Jan 1, 2020</time>
                </div>

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  <li><a href="#">App</a></li>
                  <li><a href="#">IT</a></li>
                  <li><a href="#">Business</a></li>
                  <li><a href="#">Mac</a></li>
                  <li><a href="#">Design</a></li>
                  <li><a href="#">Office</a></li>
                  <li><a href="#">Creative</a></li>
                  <li><a href="#">Studio</a></li>
                  <li><a href="#">Smart</a></li>
                  <li><a href="#">Tips</a></li>
                  <li><a href="#">Marketing</a></li>
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->
  {% endblock content %}

churchapp/templates/navbar.html
{% load static %}
{% load bootstrap4 %}

<header id="header" class="fixed-top d-flex align-items-center">
  <div class="logo me-auto"><img src="{% static 'assets/img/church (1).png' %}" alt=""></div>
    <div class="container d-flex align-items-center">
      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'churchapp:home' %}">Home</a></li>
          {% if user.is_admin %}
          <li class="dropdown"><a href="#"><span>Dashboard</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'churchapp:event_form' %}">New Event</a></li>
              <li><a href="{% url 'churchapp:cermon_form' %}">New Sermon</a></li>
              <li><a href="{% url 'churchapp:payment_form' %}">New Donation Method</a></li>
              <li><a href="{% url 'churchapp:impact_category_form' %}">Add Impact Category</a></li>
              <li><a href="{% url 'churchapp:impact_form' %}">New Impact Item</a></li>
              <li><a href="{% url 'churchapp:gallery_form' %}">New Gallery Image</a></li>
              <li class="dropdown"><a href="#"><span>More..</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="{% url 'churchapp:team_form' %}">Add Leaders</a></li>
                  <li><a href="{% url 'churchapp:faq_form' %}">FAQs</a></li>
                </ul>
              </li>
            </ul>
          </li>
          {% endif %}
          <li><a class="nav-link scrollto" href="#about">About Us</a></li>
          <li><a class="nav-link scrollto" href="#tabs">Impact</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Gallery</a></li>
          <li><a href="{% url 'churchapp:events' %}" class="nav-link scrollto">Events</a></li>
          <li class="dropdown"><a href="#"><span>Sermons</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#cermon">All Sermons</a></li>
              <li class="dropdown"><a href="#"><span>Weekly Sermons</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#cermon">Sunday Sermons</a></li>
                  <li><a href="#cermon">Mid-Week Sermons</a></li>
                  <li><a href="#cermon">Friday's kesha</a></li>
                </ul>
              </li>
              <li><a href="#cermon">Monthly Sermons</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
          <li><a href="{% url 'login' %}" class="nav-link scrollto">Login</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="#pricing" class="get-started-btn scrollto">DONATE</a>
    </div>
  </header><!-- End Header -->

churchapp/templates/review_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static%}
<div class="container mt-3">

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card" style="margin-top:2%; padding:20px">
                <div class="card-body">
                    <h5 class="card-title text-center"><b>Add Your Testimony</b></h5>
                    <hr>
                    <div class="card-text">
                        <form action="" method="post" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" class="btn btn-sm btn-dark" value="Save" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}